### ISSUE TITLE
Option to ignore gitignored files

### ISSUE THREAD

**Issue by SaturnFromTitan** [vlajos/misspell-fixer#37]
I love the project, thanks a lot! I just ran it on one of my projects and saw some `Permission denied` errors for temporary, gitignored cache files.

As I don't really care for typos in files that aren't part of my repository, it'd be great to have a flag to just ignore them.

**Comment by vlajos** [comment]
Hi @SaturnFromTitan,
That is a good idea as well!
I think it is relatively straigh-forward to exclude `.gitignored` files with using the output of `git ls-files --others --ignored --exclude-standard`.
Could you please check if this command's output is the list you would like to ignore?
To avoid introducing a strict dependency on git, probably I would implement this as a new optional switch.
Would this be something useful for you this way?

Best regards,
Lajos

**Comment by SaturnFromTitan** [comment]
Yes, `git ls-files --others --ignored --exclude-standard` works perfectly! And I agree that an optional dependency on `git` is the way to go ✌️

**Comment by vlajos** [comment]
@SaturnFromTitan I have implemented something naive in this branch: 37-respect-gitignore
Could you please test it a bit?
A new option `-G` should enforce misspell-fixer to respect `.gitignore` files.

It may happen that bash command line length limitations break it for longer .gitignore file lists, but let's see first if it works at all.

**Comment by SaturnFromTitan** [comment]
Hi @vlajos looking at the code, it looks good. How can I test this locally?

**Comment by vlajos** [comment]
@SaturnFromTitan 
Assuming you use it from command line:
(docker, github action, debian package are a little different.)

1. You can download the new version to somewhere locally:
```
git clone https://github.com/vlajos/misspell-fixer.git
cd misspell-fixer
git checkout 37-respect-gitignore
```
2. Backup your project folder.
3. Then from your project folder to fix call the downloaded instance with the new flag:
```
cd <<your project>>
path/to/the/above/version/misspell-fixer -G <<old arguments>>
```

**Comment by SaturnFromTitan** [comment]
@vlajos The -G flag didn't work though :/

I built the docker image locally from the branch `37-respect-gitignore`. I just added a new file `qwe.py` with the content
```
# acheive
```
and added it to my .gitignore file. The file is also contained in the output of `git ls-files --others --ignored --exclude-standard`

Running the container with `-frunRVDG` still corrects the file though :/

And indeed, the number of gitignored files is pretty high for my test project:
`git ls-files --others --ignored --exclude-standard | wc -l` = 2695

Since the misspellfixer is especially helpful for large projects, I think supporting large lists of gitignored files is critical for this feature to be useful though.

**Comment by vlajos** [comment]
Hi @SaturnFromTitan 
The docker image did not have git installed. I have added it to the image.
This is probably not enough in itself for that long file list, but it would be good to see if the argument is caught at all.
Could you please maybe rerun it after rebuilding the image from the latest version of that branch and send me the command line and the standard output/error?
Calling the script from docker tends to shuffle the paths a bit. But this depends on the exact calling.

**Comment by SaturnFromTitan** [comment]
I pulled the latest version of the branch, rebuild the image and now I get the following errors @vlajos:
```
(sales_cockpit_be) ➜  sales-cockpit-be git:(master) ✗ docker run -ti -v {path_to_my_project}:/work --rm temp-spell-fixer -frunRVDG .
misspell-fixer: -f Enable fast mode. (Equivalent with -P4)
misspell-fixer: -r Enable real run. Overwrite original files!
misspell-fixer: -u Enable unsafe rules.
misspell-fixer: -n Disable backups.
misspell-fixer: -R Enable rare rules.
misspell-fixer: -V Enable very-rare rules.
misspell-fixer: -D Enable rules from lintian.debian.org / spelling.
misspell-fixer: -G Respect .gitignore.
misspell-fixer: Target directories: .
/misspell-fixer//lib/initialisation_functions.sh: line 250: /bin/grep: Argument list too long
/misspell-fixer//lib/initialisation_functions.sh: line 250: /misspell-fixer//lib/initialisation_functions.sh: line 250: /bin/sed: Argument list too long
/usr/bin/head: Argument list too long
/misspell-fixer//lib/initialisation_functions.sh: line 252: /usr/bin/sort: Argument list too long
misspell-fixer: !! Your grep version is  which is less than the optimal: 2.28. This may degrade misspell fixer's performance significantly! (100x) !!
/misspell-fixer//lib/initialisation_functions.sh: line 265: /bin/grep: Argument list too long
/misspell-fixer//lib/main_functions.sh: line 4: /bin/grep: Argument list too long
/misspell-fixer//lib/main_functions.sh: line 9: /bin/grep: Argument list too long
/misspell-fixer//lib/main_functions.sh: line 11: /bin/sed: Argument list too long
/misspell-fixer//lib/main_functions.sh: line 16: /bin/grep: Argument list too long
/misspell-fixer//lib/main_functions.sh: line 19: /bin/sed: Argument list too long
misspell-fixer: Iteration 0: prefiltering.
/misspell-fixer//lib/main_functions.sh: line 59: /usr/bin/tee: Argument list too long
/misspell-fixer//lib/main_functions.sh: line 73: /usr/bin/xargs: Argument list too long
/misspell-fixer//lib/main_functions.sh: line 41: /bin/cat: Argument list too long
/misspell-fixer//lib/main_functions.sh: line 59: /usr/bin/xargs: Argument list too long
/misspell-fixer//lib/main_functions.sh: line 27: /usr/bin/find: Argument list too long
/misspell-fixer//lib/main_functions.sh: line 85: /usr/bin/sort: Argument list too long
misspell-fixer: Iteration 0: nothing to replace.
misspell-fixer: Iteration 0: done.
/misspell-fixer//lib/main_functions.sh: line 215: /bin/rm: Argument list too long
/misspell-fixer/misspell-fixer: line 43: /bin/rm: Argument list too long
```

**Comment by vlajos** [comment]
@SaturnFromTitan I have updated the branch. Could you please try it again?
(Sorry for the delay...)

**Comment by vlajos** [comment]
@SaturnFromTitan I have just merged the related branch. Hopefully the new ignore logic is robust enough.

**Comment by vlajos** [comment]
Fixed previously
