### ISSUE TITLE
Ignore video files

### ISSUE THREAD

**Issue by SaturnFromTitan** [vlajos/misspell-fixer#38]
We have a few small video files used for testing, in particular these are `.mov` and `.mp4` format. The misspell-fixer changed these files. I guess that runs a risk of corrupting the files though.

**Comment by vlajos** [comment]
Hi,

Thanks for this idea.
I have just pushed a small patch for this.
Please feed back if it works, but more importantly if it does not.

Best regards,
Lajos

**Comment by SaturnFromTitan** [comment]
Works, thanks @vlajos!
