### ISSUE TITLE
.jar files should be considered as binary

### ISSUE THREAD

**Issue by olivierlefloch** [vlajos/misspell-fixer#42]
It seems `misspell-fixer` will fix spelling mistakes inside `.jar` files which are binary Java distribution files ( https://en.wikipedia.org/wiki/JAR_(file_format) ). I believe the extension should be included in the set of binary extensions.

**Comment by vlajos** [comment]
@olivierlefloch 
I have just pushed a fix for this. Let me know please if it has any issues.
