### ISSUE TITLE
Allow specifying a custom path for .misspell-fixer.ignore

### ISSUE THREAD

**Issue by olivierlefloch** [vlajos/misspell-fixer#43]
We are running `misspell-fixer` as part of a Github Action. As such, I'd like to keep all configuration for these actions within our `.github` folder, and specify a path of `.github/.misspell-fixer.ignore` for the ignore file. Reading the documentation (and after a cursory look at the source code), it doesn't seem possible to specify a different location for this file. I'd love for there to be a command line argument to override the default path to this configuration file.

**Comment by kdeldycke** [comment]
My workaround was to generate the `.github/.misspell-fixer.ignore` dynamiccaly before invoking the `misspell-fixer` GH Action. See: https://github.com/kdeldycke/kevin-deldycke-blog/blob/26bbb69901294aafe689d7f159984090c5ec6543/.github/workflows/autofix.yaml#L44-L49

**Comment by olivierlefloch** [comment]
Ah – that would work!

**Comment by vlajos** [comment]
@olivierlefloch @kdeldycke @Techtronix
I have added some logic to automatically pick-up `.github/.misspell-fixer.ignore` and also added option `-w` to allow overriding the white list file.
Is this something useful for you?
Could you please test it if so?

**Comment by kdeldycke** [comment]
Thanks @vlajos for the feature! Just tried it at: https://github.com/kdeldycke/kevin-deldycke-blog/commit/a943d077c0a11261dde81fa474e17ff8040b6d69

As you can see in the result workflow, it works: https://github.com/kdeldycke/kevin-deldycke-blog/runs/970819972?check_suite_focus=true#step:4:15

Thanks again @vlajos for that quick patch! 🥳
